# Generated by Django 3.2.12 on 2022-03-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ligand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zinc_id', models.CharField(max_length=16)),
                ('inchi', models.CharField(blank=True, max_length=300, null=True)),
                ('inchi_key', models.CharField(blank=True, max_length=27, null=True)),
                ('cansmi', models.CharField(max_length=200)),
                ('nb_atoms', models.PositiveIntegerField()),
                ('sdf_file', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ligand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binding_affinity', models.FloatField()),
                ('coor_file', models.CharField(max_length=100)),
                ('sdf_file', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pose',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_id', models.CharField(max_length=4)),
                ('protein_name', models.CharField(max_length=50)),
                ('virus_name', models.CharField(blank=True, max_length=50, null=True)),
                ('coor_file', models.CharField(blank=True, max_length=100, null=True)),
                ('pdb_file', models.CharField(max_length=100)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'protein',
                'managed': False,
            },
        ),
    ]
